### PR TITLE
AdoptOpenJDK --> Termurin/Semeru

### LINKED ISSUE #674: AdoptOpenJDK is now Adoptium Temurin and IBM Semeru
### :speaking_head: Foreword

Apparently since July 2021 AdoptOpenJDK hotspot is now known as Adoptium Temurin and AdoptOpenJDK OpenJ9 is now IBM Semeru. 

## :ghost: Brief Description

New binaries do not appear to be posted on https://github.com/AdoptOpenJDK/openjdk11-binaries/releases anymore. This cookbook now installs a outdated (and potentially vulnerable) version of AdoptOpenJDK.

New releases of hotspot can be found on https://adoptium.net/temurin/releases
New releases of OpenJ9 can be found on https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

## :pancakes: Cookbook version

11.0.2

## Steps To Reproduce

1. use `adoptopenjdk_install` resource to install java
2. get outdated JDK version from `https://github.com/AdoptOpenJDK/openjdk<version>-binaries/releases`

### PR DESCRIPTION
**Pull request by damacus**
# Description

Remove AdoptOpenJDK and replace with Adoptium Termurin & IBM Semeru

## Issues Resolved

#674 

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by xorima — APPROVED** [review]

**Review by xorima — APPROVED** [review]

**Review by xorima — APPROVED** [review]

**Review by xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [12.0.0](https://github.com/sous-chefs/java/releases/tag/12.0.0)

**Comment by yacn** [comment]
@xorima why did you merge this when it has broken tests

**Comment by mwiczynski-cartera** [comment]
I think this change has a typo in it? it just broke our chef runs...
https://github.com/sous-chefs/java/blame/00570a6f0c07020186fae2aeedd2c49eb82d1e13/resources/openjdk_source_install.rb#L10
Should that be `openjdk`, not `opendjdk`?

**Comment by xorima** [comment]
Hey all, this has been reverted, as mentioned on slack post on this, it was not indended to impact this PR and was due to bad automation. plans are in place to ensure this does nto happen again.

**Pull request merged**
