### PR TITLE
Add support for new artifacts naming schema to adoptopenjdk, add JRE install

### LINKED ISSUE #539: AdoptOpenJDK changed artifacts naming template and resource adoptopenjdk_install fails
### Cookbook version

3.2.1 ? (actually it's 3.2.0 in GitHub master)

### Chef-client version

14

### Platform Details

Ubuntu 18.04

### Scenario:

AdoptOpenJDK changed artifacts naming template and resource adoptopenjdk_install fails.
Current version in default attributes is:
 `default['java']['adoptopenjdk']['8']['x86_64']['openj9']['url'] = 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_openj9_8u192b12.tar.gz'`
I want to use newer version and set:
`default['java']['adoptopenjdk']['8']['x86_64']['openj9']['url'] = 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz'`

As you see, there is a new part `_openj9-0.12.1` in the filename. And this schema is used in all builds newer than jdk8u192-b12
You can check at https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

### Steps to Reproduce:

* Set `default['java']['adoptopenjdk']['8']['x86_64']['openj9']['url'] = 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz'`
* Run converge

### Expected Result:

* jdk8u202 is installed

### Actual Result:

```
Recipe: java::adoptopenjdk
         * adoptopenjdk_install[adoptopenjdk] action install
           * directory[/usr/lib/jvm] action create (up to date)
           * remote_file[/tmp/kitchen/cache/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz] action create_if_missing
             - create new file /tmp/kitchen/cache/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz
             - update content in file /tmp/kitchen/cache/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz from none to cdfa82
             (file sizes exceed 10000000 bytes, diff output suppressed)
             - change mode from '' to '0644'
           * apt_package[tar] action install (up to date)
       [2019-04-17T15:07:20+00:00] FATAL:  Command ' mv "/tmp/kitchen/cache/jdk-0.12+1" "/usr/lib/jvm/jdk-0.12+1-openj9" ' failed
```

### PR DESCRIPTION
**Pull request by Nklya**
### Description

* Add support for new artifacts naming schema to adoptopenjdk
* Add openj9-jre and hotspot-jre install types to adoptopenjdk
* Show download progress for adoptopenjdk files
* Add links to adoptopenjdk JDK12 and fill bin_cmds for it
* Update adoptopenjdk 8 links to 8u212

### Issues Resolved

Fixes #539 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Nklya** [comment]
I am planning to add tests a little bit later.
And update links to adoptopenjdk 8u212 hotspot because they are not available now.

**Comment by Nklya** [comment]
It looks like errors in CI lint are not related to my changes:
```
Running Lint Phase
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.62.0/lib/rubocop/target_finder.rb:103: warning: Insecure world writable dir /usr/local/bundle in PATH, mode 042777
Inspecting 67 files
.....C.............................................................

Offenses:

resources/oracle_install.rb:263:9: C: Layout/ClosingParenthesisIndentation: Indent ) to column 10 (not 8)
        )
        ^

67 files inspected, 1 offense detected
Phase failed with exit code (1)!
Exited with code 1
```

**Comment by Xorima** [comment]
Hey
Thank you for the PR. We are closing due to inactivity.
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Thanks

Sous Chefs

**Pull request closed without merging**
