### PR TITLE
Adding java_jce resource.

### PR DESCRIPTION
**Pull request by jqassar**
### Description

Adds a java_jce custom resource to the java cookbook to support installing JCE for multiple/non-standard Java installations.  At this time it merely replicates the contents of the oracle_jce.rb, which now invokes the resource.  Future work could involve 'Chef-ing' the current execute block which unpacks the JCE files and applies them.

### Issues Resolved

https://github.com/sous-chefs/java/issues/371

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by jqassar** [comment]
@tas50 , the PR has been updated to address the conflicts with 2.1.0.

**Comment by damacus** [comment]
is it worth throwing in some integration tests for this?

**Comment by jqassar** [comment]
The existing integration tests are already covering the expected result of JCE installation (that cipher strength is reported to increase).

**Comment by damacus** [comment]
Thanks for taking your time to submit this patch!

**Pull request merged**
