### PR TITLE
Added windows choco support for issue #407

### LINKED ISSUE #407: Install Java on Windows with Chocolatey
Is there any reason Java is not installed by default with Chocolaty in a similar way to how Homebrew is the default instillation for MacOS or at least provide it as an option? I wouldn't mind taking a crack at it implementing it but was wondering if there was an underlying reason for its exclusion.

### PR DESCRIPTION
**Pull request by TechDawg270**
Added functionality to support Windows chocolatey installation. Closes #407

### CODE REVIEW

**Comment by erichelgeson** [comment]
I unfortunately have no way to test this. If another Windows user could review this I'll merge.

**Comment by TechDawg270** [comment]
Understandable. Maybe I can get the person from the other thread asking for this functionality to test it

**Comment by tas50** [comment]
With how simple it is to install Java via choco it seems like this probably shouldn't get added. A user can just add that single resource to their own cookbook.

**Comment by majormoses** [comment]
closing this as it does not make much sense to include in the community cookbook and lack of response on feedback.

**Pull request closed without merging**
