### PR TITLE
Update default download URL and checksum for oracle jdk 8 x86_64

### LINKED ISSUE #517: Java download URL on attribute default['java']['jdk']['8']['x86_64']['url'] is broken
### Cookbook version
3.1.2

### Chef-client version
12.1

### Platform Details
RHEL-7.3

### Scenario:
Trying to install Java 8 with cookbook.

### Steps to Reproduce:
Converge with attribute on RedHat 7:
```
        "java": {
          "jdk_version": "8",
          "install_flavor": "oracle",
          "oracle": {
            "accept_oracle_download_terms": true
          }
        }
```

### Expected Result:
Install Java 8 JDK

### Actual Result:
```
---- Begin output of curl --fail --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz -o /tmp/packer-chef-solo/local-mode-cache/cache/jdk-8u191-linux-x64.tar.gz --connect-timeout 600   ----
Expected process to exit with [0], but received '22'
```

### PR DESCRIPTION
**Pull request by y-batsianouski**
### Description

Update oracle jdk 8 x86_64 url and checksum

### Issues Resolved

#517 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/java/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JohnRoesler** [comment]
@y-batsianouski could you add a change log entry?

**Comment by JohnRoesler** [comment]
Also, wondering if we should go ahead and update all the URLs as the current version of 8 and likely others is out of date in the cookbook.

**Comment by y-batsianouski** [comment]
@JohnRoesler Should I bump version of the cookbook? up to 3.1.3? Otherwise I don't know where exactly to add entry in CHANGELOG :slightly_smiling_face: 

Also I can update URLs for other java versions today later, np. I did not do it because I haven't a time when I prepared PR. But I think I will be usefull for others.

**Comment by JohnRoesler** [comment]
@y-batsianouski usually there is an unreleased section at the top, like https://github.com/sous-chefs/haproxy/blob/master/CHANGELOG.md

**Comment by majormoses** [comment]
Since I had to rebase the branch anyways I added a changelog entry for you

**Comment by y-batsianouski** [comment]
Hello @majormoses !
Sorry for the late reply and thank you to release that changes!

**Pull request merged**
