### PR TITLE
Fixing JRE installation

### PR DESCRIPTION
**Pull request by frezbo**
Fixes https://github.com/agileorbit-cookbooks/java/issues/454

### CODE REVIEW

**Comment by frezbo** [comment]
@jtimberman @erichelgeson Would it be possible to get this merged?

**Comment by jtimberman** [comment]
I'm not involved in development of this cookbook anymore.

Cheers

**Comment by frezbo** [comment]
@tas50 Can I expect this to be part of next release? Thanks

**Comment by tas50** [comment]
Closing in favor of #466

**Pull request closed without merging**
