### PR TITLE
If installation issues with openjdk_install resource

### LINKED ISSUE #645: Bad resource naming for openjdk_source_install
## :ghost: Brief Description

Try to use the resource openjdk_install but this resource us already use by openjdk_source_install.rb

## :pancakes: Cookbook version
8.4.0

## :woman_cook:  Chef-Infra Version
15.0.300

## :tophat: Platform details
Ubuntu 18.04 LTS

## Steps To Reproduce

1. Create a cookbook/recipe using:

```ruby
openjdk_install "core" do
  version "14"
  default true
  install_type "package"
end
```

2. Compile the cookbook
3. Error is:

```
NoMethodError
    -------------
    undefined method `install_type' for Custom resource java_openjdk_source_install from cookbook java
```

## :police_car: Expected behavior
Able to use openjdk_install as main wrapper for openjdk_pkg_install and openjdk_source_install

### PR DESCRIPTION
**Pull request by ramereth**
This actually fixes two issues:

- Properly fix `resource_name` and `provides` parameters in
  `openjdk_source_install` resource as `openjdk_source_install`.
- Use `new_resource.install` when references parameters in `openjdk_install`

This resolves #645.

Signed-off-by: Lance Albertson <lance@osuosl.org>

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
Looks like I need to fix a few things. I'll do that in a few days unless someone else can fix it.

**Review by majormoses — APPROVED** [review]
Not sure what else you might need to fix but these all make sense to me.

LGTM

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by kitchen-porter** [comment]
Released as: [8.5.0](https://github.com/sous-chefs/java/releases/tag/8.5.0)

**Pull request merged**
