### PR TITLE
default to version 8

### PR DESCRIPTION
**Pull request by cbarraford**
Fixes https://github.com/agileorbit-cookbooks/java/issues/318

### CODE REVIEW

**Comment by erichelgeson** [comment]
Java 7 has also been EOL for 2 years (sans paid support) - and is the only jdk avertible for download without oracle login. It may be better at this point to switch the defaults to openjdk & 8.

**Comment by CBarraford** [comment]
@erichelgeson ok, i'll switched to version 8

**Comment by tas50** [comment]
This would be a nice one to get in.

**Comment by erichelgeson** [comment]
If we want to do a major release with #412 as well we can change these defaults & release a 2.0

**Comment by majormoses** [comment]
@cbarraford can you please rebase to fix conflicts?

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/java/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by josephholsten** [comment]
hmm `lint` seems not to be an accurate description of that build in circle-ci, there are significant failures in there. I'm sorry, but I can't merge this until the tests depending on java 6 are updated.

**Comment by cbarraford** [comment]
@josephholsten i've fixed the tests, looks like i still need to make a changelog entry change, but im not exactly sure how. What version should I call this, and when is the release date, etc?

**Pull request merged**
